theme: jekyll-theme-minimal
title: "UMD Physics & AI Reading Group"
description: "A reading group focusing on the intersection of machine learning and computational science and engineering."
github: false
